### PR TITLE
Add instructions for installing via spack

### PR DESCRIPTION
**Pull request by schoonovernumerics**
I've added some documentation for installing HOHQMesh via spack. Additionally, there are notes on how to contribute new version releases for FTOL to the Spack package manager.

Ideally, you should be able to install Spack using the instructions provided once HOHQMesh has been added to Spack; we're currently waiting on this pull request to be approved : https://github.com/spack/spack/pull/24501

### CODE REVIEW

**Comment by schoonovernumerics** [comment]
As an update, https://github.com/spack/spack/pull/24501 was merged in and hohqmesh can now be installed using spack

**Comment by DavidAKopriva** [comment]
Sorry I didn't see this. No specific comment.

**Comment by DavidAKopriva** [comment]
approved.

**Review by sloede — APPROVED** [review]
LGTM! I moved the "Updating Spack Packages" section to the Developer section of the official documentation - I hope that's ok for you, @schoonovernumerics, otherwise please let me know.

Thanks for providing this option of making installing HOHQMesh easier outside Julia!

**Pull request merged**
