### PR TITLE
enable dependabot for GitHub actions

### PR DESCRIPTION
**Pull request by ranocha**
This allows us to get updates for GitHub actions automatically.

### CODE REVIEW

**Review by sloede — APPROVED** [review]

**Comment by ranocha** [comment]
Can we merge this?

**Comment by andrewwinters5000** [comment]
> Can we merge this?

Fine by me. What do you think @DavidAKopriva ?

**Comment by DavidAKopriva** [comment]
Yes, that's fine with me. See also PR#53

**Comment by andrewwinters5000** [comment]
@ranocha @sloede Should I add this same dependbot to the FTOL Github actions?

**Comment by sloede** [comment]
> @ranocha @sloede Should I add this same dependbot to the FTOL Github actions?

Yes, that would be a good idea!

**Pull request merged**
