### PR TITLE
Add feature to create bottom topography from data

### PR DESCRIPTION
**Pull request by andrewwinters5000**
This is a small step to add the capability of creating a bottom topography from data read in from a file. Then a 3D mesh is created using simple extrusion. To create the high-order boundary information a bicubic interpolation is used given the available data read in from the provided file.

Currently, this file data is assumed to be gridded data that has (presumably) been pre-processed by a user.

### CODE REVIEW

**Comment by fluidnumerics-joe** [comment]
@andrewwinters5000 - I just pushed up a patch that resolves the compiling issue with the exception handler call. I think we now want to settle on who to put as the `poster`

**Review by DavidAKopriva — COMMENTED** [review]
At line 743 in ConstructTopographyFromDict the topog_file  should be DEFAULT_CHARACTER_LENGTH. Might consider a new constant FILE_PATH_LENGTH for use with file paths. Right now they are all DEFAULT_CHARACTER_LENGTH. See also L764.

At line 106 in initWithDataFile I'd use DataFileTopography/initWithDataFile or something like that

ibid L122. There is a function UnusedUnit (define as INTEGER, EXTERNAL) in FileAndStringProcessing.f90 for this. Now fortran itself has such a function

     open(newunit=unit,file='test')

where unit is INTEGER.

**Review by DavidAKopriva — COMMENTED** [review]
You need a return just before L112 in InitWithDataFile

**Comment by fluidnumerics-joe** [comment]
@DavidAKopriva @andrewwinters5000 it looks like there are some coverage issues that can be resolved. I'll take a look at where we can improve coverage; I suspect we don't have tests running for the new example associated with this feature. It'd be great to get this merged in

**Comment by andrewwinters5000** [comment]
> I'll take a look at where we can improve coverage; I suspect we don't have tests running for the new example associated with this feature. It'd be great to get this merged in

I agree it would be good to get this feature merged into `main`. Do we need to merge your `spline_curve` feature first @fluidnumerics-joe ? Or are the two features orthogonal in some sense?

**Comment by andrewwinters5000** [comment]
The coverage improved because the new 3D test also exercises the Abaqus output routines in `3DSource/Mesh3DOutputMethods.f90`. It is strange that the destruct and release routines for the new `SMTopographyFromFile` are not covered. I believe that these should get invoked when lines 173-176 in `destructModel` are executed because that is when the topography pointer gets released. Do I understand this release call correctly @DavidAKopriva ?

**Comment by andrewwinters5000** [comment]
mountain

**Comment by DavidAKopriva** [comment]
Andrew,

1. The "how to add a test case" looks good. I'm almost wondering if the list of tests should be in a file rather than code, since there is actually no reason to have to edit code to add a test case. OTOH, there's one less file path to have to maintain.
2. In the docs for getting the topography from a file, there is no example showing how to invoke it. I presume it's "file =" in the TOPOGRAPHY block. 
Will start looking through the code next...

**Comment by fluidnumerics-joe** [comment]
> It might be easiest to move it out of the code and into a separate file. Having it directly in the MeshTesting.f90 file tends to regularly cause merge conflicts.

I agree with moving the list of tests to a file that just lists the set of control files under `Benchmarks`. Alternatively, if we don't want to maintain a list, we could modify the `ci.yaml` to create such a list on the fly by listing the control files under `Benchmarks/ControlFiles`. 

If we need to require that a `test file` is available for comparison, we could modify the MeshingTests to throw an error if one is not found.

**Comment by DavidAKopriva** [comment]
"It might be easiest to move it out of the code and into a separate file. Having it directly in the MeshTesting.f90 file tends to regularly cause merge conflicts." --- That's my thinking, too. Let's finish up with this PR and think about that in the meantime. The issue will come up again when we merge the TopographyResolution branch in, will I will propose to look at after this one.

**Comment by DavidAKopriva** [comment]
I'll go though the new stuff this morning, esp. the fact that the final routines are not being called.

**Comment by DavidAKopriva** [comment]
Thanks for noticing the fact the destructors weren't called. The bug was way up in the chain where the FINAL routine for the MeshProject class wasn't defined.

**Pull request merged**
