### PR TITLE
Avoid seg fault for 3D extrusion without a MODEL block

### LINKED ISSUE #48: Simple Extrusion crash
HOHQMesh now crashes with a set fault when extruding a 2D mesh that has been generated without an outer boundary. An example control file is for a 2D box extruded to a cube geometry:
\begin{CONTROL_INPUT}

   \begin{RUN_PARAMETERS}
      mesh file name   = MeshFiles/Box3D.mesh
      plot file name   = PlotFiles/Box3D.tec
      stats file name  = None
      mesh file format = ISM
      polynomial order = 4
      plot file format = skeleton
   \end{RUN_PARAMETERS}

   \begin{MESH_PARAMETERS}
      element type         = hex
   \end{MESH_PARAMETERS}

    \begin{SIMPLE_EXTRUSION}
      direction          = 3
      height             = 2.0
      subdivisions       = 3
      start surface name = bottom
      end surface name   = top
   \end{SIMPLE_EXTRUSION}

   \begin{BACKGROUND_GRID}
       x0 = [0.0, 0.0, 0.0]
       dx = [1.0, 1.0, 1.0]
       N  = [5,5,5]
   \end{BACKGROUND_GRID}

    \begin{SPRING_SMOOTHER}
       smoothing            = ON
       smoothing type       = LinearAndCrossBarSpring
       spring constant      = 1.0
       mass                 = 1.0
       rest length          = 0.0
       damping coefficient  = 5.0
       number of iterations = 5
       time step            = 0.1
   \end{SPRING_SMOOTHER}

\end{CONTROL_INPUT}

### PR DESCRIPTION
**Pull request by andrewwinters5000**
This is a bug fix that closes #48 .  A model block is only required for the SWEEP type of extrusion. For simple extrusions or rotations the model block is not required. So, I added a check if the model block is `ASSOCIATED` to avoid referencing a NULL pointer.

### CODE REVIEW

**Review by DavidAKopriva — CHANGES_REQUESTED** [review]
The issue was indeed the use of a null pointer, but it doesn't arise until later. The fix proposed  would have still failed at some point. I moved the check to where it is used, and posted an exception to tell the user that a model block is needed if a sweep along a curve is done (if only for that reason). Unfortunately, this drops the codecov by a fraction of a %.

**Comment by andrewwinters5000** [comment]
> Unfortunately, this drops the codecov by a fraction of a %.

That is okay from my perspective. A bug fix plus a new meaningful error message is more important.

**Review by sloede — APPROVED** [review]
Same here: I didn't notice any obvious issues, but I didn't really check the code either. Having said that, this LGTM

**Comment by DavidAKopriva** [comment]
When merged with the PR53, the total should go up anyway.

**Pull request merged**
