### PR TITLE
Feature/spline curve from file

### PR DESCRIPTION
**Pull request by fluidnumerics-joe**
Adds a simple file IO interface to allow spline curve data to come in from a text file separate from the control file.

### CODE REVIEW

**Review by DavidAKopriva — COMMENTED** [review]
My approach has been to use the "ContainsKey" method in an if block for options. I think the structure is a little simpler that way than what's in ImportSplineBlock now. The structure would be

if splineDict % containsKey(SPLINE_FILE_KEY)
  call read data from file
else
 read data from dictionary
end if

The keys are all represented by constants (So that they can be changed later, if desired).

**Comment by fluidnumerics-joe** [comment]
Copy that. I can make a few adjustments to match what you've done elsewhere.

**Review by DavidAKopriva — COMMENTED** [review]
Looks fine. The call to SetStringValueFromDictionary at 820 could simply be replaced by splineDict % stringvalueforKey(...), which is called in that routine, since the check has already been made for the existence of the key. But it doesn't matter, and an exception won't ever be thrown. If it were, the message would be invalid since there will be no try to load from the spline data block.

**Comment by fluidnumerics-joe** [comment]
Closing this PR, in favor of https://github.com/trixi-framework/HOHQMesh/pull/32

**Pull request closed without merging**
