### PR TITLE
add SpellCheck CI

### PR DESCRIPTION
**Pull request by andrewwinters5000**
We have used this spell checker to help catch typos in the docs and code comments in other parts of the trixi-framework and it has been quite helpful.

### CODE REVIEW

**Comment by DavidAKopriva** [comment]
Interesting and looks useful. It doesn't know fortran, however.

**Comment by andrewwinters5000** [comment]
> Interesting and looks useful. It doesn't know fortran, however.

It seems to be "smart" enough to work directly for the most part. I added an extra word "INOUT" to its dictionary such that it does not think this fortran keyword is something that is misspelled.

**Comment by andrewwinters5000** [comment]
Also kudos @DavidAKopriva ! With the amount of docs and comments in this code the auto-spellchecker only found about 35 typos which is quite nice.

**Review by ranocha — APPROVED** [review]
I didn't check all files since there is a huge amount of whitespace changes.

You could also consider adding the new CI run to the required CI checks for PRs etc.

**Comment by andrewwinters5000** [comment]
> I didn't check all files since there is a huge amount of whitespace changes.

Thanks, I only realized too late that my VSCode was removing all the whitespace making this PR look much larger than it is.

> You could also consider adding the new CI run to the required CI checks for PRs etc.

I thought I did with the `on: [pull_request]` part of the new yml file. Do I need to modify the `ci.yml` too?

**Comment by ranocha** [comment]
> > You could also consider adding the new CI run to the required CI checks for PRs etc.
> 
> I thought I did with the `on: [pull_request]` part of the new yml file. Do I need to modify the `ci.yml` too?

This let's it run for every PR. If you want to make it a required check, you need to go to the settings of this repo, then branches, edit the rules for `main`, and add the spell check Ci run to the required checks. I can also do that if you like.

**Comment by andrewwinters5000** [comment]
> > > You could also consider adding the new CI run to the required CI checks for PRs etc.
> > 
> > 
> > I thought I did with the `on: [pull_request]` part of the new yml file. Do I need to modify the `ci.yml` too?
> 
> This let's it run for every PR. If you want to make it a required check, you need to go to the settings of this repo, then branches, edit the rules for `main`, and add the spell check Ci run to the required checks. I can also do that if you like.

No that's okay, I can do it here (and also for HOHQMesh.jl).

**Comment by ranocha** [comment]
If you do it here, you can also consider adding more Ci checks to the required ones, e.g., `CI / linux - gfortran-12 - regular`

**Pull request merged**
