### PR TITLE
Add Valgrind memory check to CI tests on Linux

### LINKED ISSUE #41: Add Valgrind to CI
Once #40 is fixed, we should add a Valgrind pass to the CI to avoid accidentally adding new memory bugs. This could be done, e.g., by adding an additional CI check that runs the testsuite with
```shell
valgrind --error-exitcode=1 --exit-on-first-error=yes ./HOHQMesh -test
```

### PR DESCRIPTION
**Pull request by sloede**
Fixes #41.

### CODE REVIEW

**Comment by sloede** [comment]
I added a Valgrind check the Ubuntu runs, and at the moment it reports one error (see [here](https://github.com/trixi-framework/HOHQMesh/runs/6782390961?check_suite_focus=true)).

@DavidAKopriva Once #42 is merged, we can check if this error persists and if not, merge this PR as well to prevent future memory issues.

**Comment by andrewwinters5000** [comment]
The additional valgrind checks have revealed another memory leak, this time on ubuntu. From the logs the culprit is the test with `Benchmarks/ControlFiles/SeaMountCubic.control` with the following error
```
==2300== Use --track-origins=yes to see where uninitialised values come from
==2300== ERROR SUMMARY: 7 errors from 1 contexts (suppressed: 0 from 0)
==2300== 
==2300== 7 errors in context 1 of 1:
==2300== Conditional jump or move depends on uninitialised value(s)
==2300==    at 0x12F9FF: __ftlinkedlistclass_MOD_makecircular (in /home/runner/work/HOHQMesh/HOHQMesh/HOHQMesh)
==2300==    by 0x12FF77: __ftlinkedlistclass_MOD_alllinkedlistobjects (in /home/runner/work/HOHQMesh/HOHQMesh/HOHQMesh)
==2300==    by 0x1685F7: __simplesweepmodule_MOD_performsimplemeshsweep (in /home/runner/work/HOHQMesh/HOHQMesh/HOHQMesh)
==2300==    by 0x111D5B: __meshcontroller3d_MOD_generate3dmesh (in /home/runner/work/HOHQMesh/HOHQMesh/HOHQMesh)
==2300==    by 0x13B552: __hohqmeshmodule_MOD_hohqmesh (in /home/runner/work/HOHQMesh/HOHQMesh/HOHQMesh)
==2300==    by 0x151E23: __meshingtests_MOD_testwithcontrolfile (in /home/runner/work/HOHQMesh/HOHQMesh/HOHQMesh)
==2300==    by 0x18FBD1: __testsuitemanagerclass_MOD_performtests (in /home/runner/work/HOHQMesh/HOHQMesh/HOHQMesh)
==2300==    by 0x1537CF: __meshingtests_MOD_runtests (in /home/runner/work/HOHQMesh/HOHQMesh/HOHQMesh)
==2300==    by 0x13A6F5: MAIN__ (in /home/runner/work/HOHQMesh/HOHQMesh/HOHQMesh)
==2300==    by 0x13ABAE: main (in /home/runner/work/HOHQMesh/HOHQMesh/HOHQMesh)
==2300== 
==2300== ERROR SUMMARY: 7 errors from 1 contexts (suppressed: 0 from 0)
```

**Comment by DavidAKopriva** [comment]
That error is in FTObjectLibrary, which I just fixed. I don't know how to run this to make sure it did the trick.

**Comment by sloede** [comment]
> That error is in FTObjectLibrary, which I just fixed. I don't know how to run this to make sure it did the trick.

Indeed, this seems to have done the trick! If you're OK with it, this PR is good to be merged from my point of view.

**Comment by DavidAKopriva** [comment]
Yes, I'm good with merging this. Automatically doing the valgrind test is a great idea, and will save a lot of running around in the future.

**Comment by sloede** [comment]
@andrewwinters5000 @DavidAKopriva

Just as a reference for the future:

If you compile HOHQMesh with
```shell
make FFLAGS="-cpp -Og -g"
```
and then run the tests using
```shell
valgrind --error-exitcode=1 -s --track-origins=yes ./HOHQMesh.g -test
```
it gives you much more helpful Valgrind error descriptions (albeit at the cost of increasing the run time by ~2.5x):
```
==4097016== Conditional jump or move depends on uninitialised value(s)
==4097016==    at 0x130A16: __ftlinkedlistclass_MOD_makecircular (FTLinkedListClass.f90:428)
==4097016==    by 0x130F59: __ftlinkedlistclass_MOD_alllinkedlistobjects (FTLinkedListClass.f90:789)
==4097016==    by 0x16BCBB: __simplesweepmodule_MOD_performsimplemeshsweep (SimpleSweep.f90:362)
==4097016==    by 0x111D7A: __meshcontroller3d_MOD_generate3dmesh (3DMeshController.f90:301)
==4097016==    by 0x13CB4C: __hohqmeshmodule_MOD_hohqmesh (HOHQMesh.f90:188)
==4097016==    by 0x1538E1: __meshingtests_MOD_testwithcontrolfile (MeshingTests.f90:244)
==4097016==    by 0x192778: __testsuitemanagerclass_MOD_performtests (TestSuiteManagerClass.f90:273)
==4097016==    by 0x155247: __meshingtests_MOD_runtests (MeshingTests.f90:181)
==4097016==    by 0x13BAE9: MAIN__ (HOHQMeshMain.f90:94)
==4097016==    by 0x13C028: main (HOHQMeshMain.f90:47)
==4097016==  Uninitialised value was created by a stack allocation
==4097016==    at 0x130E05: __ftlinkedlistclass_MOD_alllinkedlistobjects (FTLinkedListClass.f90:749)
```
```

**Comment by andrewwinters5000** [comment]
> I don't know how to run this to make sure it did the trick.

@DavidAKopriva If you ever want to rerun the CI for a PR without pushing a new commit you can close and reopen the PR. This will trigger the CI again.

**Pull request merged**
