### PR TITLE
Remove chain requirement for inner boundaries

### PR DESCRIPTION
**Pull request by DavidAKopriva**
Inner boundary curves no longer have to be enclosed in a CHAIN block. A chain is only needed if multiple curves are connected to define an inner boundary. If a single curve defines an inner boundary, simply use that in place of a chain. If multiple curves make up the boundary, include them in a CHAIN. This eliminates a legacy requirement, makes more sense, and eliminates a model error when a CHAIN block is forgotten in the control file.

### CODE REVIEW

**Comment by DavidAKopriva** [comment]
This PR eliminates one of the issues raised in Issue #49 , where the control file was malformed because inner curves were not defined within a `CHAIN` block. Rather than supply an error message, I've simply removed that requirement, and a `CHAIN` is needed only if multiple curves define an inner boundary.

**Comment by andrewwinters5000** [comment]
This is a cool feature to add for HOHQMesh's capabilities. The ability to add elements around a "crack" could open a whole avenue of applications in wave propagation problems. I am worried that it may cause problems in some of the interactive mesh capabilities in HOHQMesh.jl. In particular, the check routines in `src/Project/Project.jl` that control for a valid project model within `modelCurvesAreOK` or `modelChainIsOK` I believe rely on closed curves.

We can add a tutorial example for a kind of "open" inner boundary curve, but these checks and other tutorials would need to updated when this "crack" feature is added to the main branch of HOHQMesh.

**Comment by DavidAKopriva** [comment]
This PR only addresses the issue of having to define all interior boundary curves as `CHAIN`s. If a curve is not defined within a chain then a chain is created for it with the same name as the curve, and the curve must be closed by itself. Nothing _has_ to be changed in the interactive tool, but a new `addInnerBoundaryCurve` function could be added that takes only the curve name, and that then passes it on to the old routine by duplicating the name as the chain name. A bit of a hack, I guess.

**Review by andrewwinters5000 — COMMENTED** [review]
Sorry for my extreme delay on this review. Everything looks good with the PR. Once we release a new version of HOHQMesh we can discuss updating the HOHQMesh.jl docs and tests for this ability.

**Pull request merged**
