### PR TITLE
Update MeshingTests.f90

### PR DESCRIPTION
**Pull request by DavidAKopriva**
Take the test file names from a file. Reads through the file to count the number of tests, allocates, then reads again. This should help avoid collisions when merging due to the need to change the code when adding new tests.

### CODE REVIEW

**Review by andrewwinters5000 — APPROVED** [review]
It all looks good to me. I updated the docs as well. This can merge once the tests pass.

**Comment by andrewwinters5000** [comment]
One curious thing looking at the testing logs. For Mac everything is clean but for ubuntu or windows the tests often write out
```
 Attempt to release object with refCount = 0
 FTObject
 --------------------------------------------
```
and I am not sure why. @DavidAKopriva any ideas? @fluidnumerics-joe do you have a linux / windows machine that can reproduce this behavior locally?

**Comment by DavidAKopriva** [comment]
The message is a nice way of saying that objects have not been retained or released properly, and gives a "gracious" way of not crashing the program due to deallocating memory that shouldn't/can't be deallocated. The question is why it should differ between the different OSs, and that I don't know. When Linux failed (due to the FS being case dependent, and my mistyping) the Windows (or Mac) showed no such messages. Tracking these down is tricky.

**Comment by fluidnumerics-joe** [comment]
@andrewwinters5000 - I do see this on my system. I can run through a trace profiler to see what is called during execution. I'll see if I can pull something together this evening/weekend.

**Comment by DavidAKopriva** [comment]
Thanks, @fluidnumerics-joe. One of the problems in tracking it down is that there are a lot of allocations and deallocations going on. Hopefully the profiler can shed some light on what's going on. I note that the compiler version for Linux/Mac is the same, but window is ahead.

**Comment by andrewwinters5000** [comment]
I am also not sure why the different OS versions give different results with regards to memory management. It is very strange and definitely an annoying / tricky thing to diagnose. Maybe different `gfortran` versions are used on the github runners for the tests.

@fluidnumerics-joe Great! A profiler would be helpful to track down exactly what is going on here.

**Comment by fluidnumerics-joe** [comment]
What I find interesting is that the error does not have a clear pattern for reproduction and seems to happen randomly. 
I can run `HOHQMesh` back-to-back with the same input file with some runs throwing the FTObject warning and some runs not. This suggests uninitialized memory, which valgrind confirms. 
When running under `valgrind`, the warning is never surfaced, but valgrind does find use of an unitialized value in the call stack for `ReadControlFile`
```
$ valgrind --track-origins=yes ./HOHQMesh < Examples/2D/HalfCircle/HalfCircle.control 
==46169== Memcheck, a memory error detector
==46169== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==46169== Using Valgrind-3.17.0 and LibVEX; rerun with -h for copyright info
==46169== Command: ./HOHQMesh
==46169== 
==46169== Conditional jump or move depends on uninitialised value(s)
==46169==    at 0x1459C5: __ftobjectclass_MOD_releaseftobject (FTObjectClass.f90:300)
==46169==    by 0x148D2C: __ftstringsetclass_MOD_addstring (FTStringSetClass.f90:242)
==46169==    by 0x149083: __ftstringsetclass_MOD_initwithstrings (FTStringSetClass.f90:177)
==46169==    by 0x123625: __controlfilereaderclass_MOD_initcontrolfilereader (ControlFileReader.f90:239)
==46169==    by 0x15491E: __hohqmeshmodule_MOD_readcontrolfile (HOHQMesh.f90:254)
==46169==    by 0x153C72: MAIN__ (HOHQMeshMain.f90:100)
==46169==    by 0x1542B1: main (HOHQMeshMain.f90:47)
==46169==  Uninitialised value was created by a heap allocation
==46169==    at 0x4843839: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==46169==    by 0x148CB3: __ftstringsetclass_MOD_addstring (FTStringSetClass.f90:240)
==46169==    by 0x149083: __ftstringsetclass_MOD_initwithstrings (FTStringSetClass.f90:177)
==46169==    by 0x123625: __controlfilereaderclass_MOD_initcontrolfilereader (ControlFileReader.f90:239)
==46169==    by 0x15491E: __hohqmeshmodule_MOD_readcontrolfile (HOHQMesh.f90:254)
==46169==    by 0x153C72: MAIN__ (HOHQMeshMain.f90:100)
==46169==    by 0x1542B1: main (HOHQMeshMain.f90:47)
==46169== 
==46169== Conditional jump or move depends on uninitialised value(s)
==46169==    at 0x145B4E: __ftobjectclass_MOD_releaseftobject (FTObjectClass.f90:308)
==46169==    by 0x148D2C: __ftstringsetclass_MOD_addstring (FTStringSetClass.f90:242)
==46169==    by 0x149083: __ftstringsetclass_MOD_initwithstrings (FTStringSetClass.f90:177)
==46169==    by 0x123625: __controlfilereaderclass_MOD_initcontrolfilereader (ControlFileReader.f90:239)
==46169==    by 0x15491E: __hohqmeshmodule_MOD_readcontrolfile (HOHQMesh.f90:254)
==46169==    by 0x153C72: MAIN__ (HOHQMeshMain.f90:100)
==46169==    by 0x1542B1: main (HOHQMeshMain.f90:47)
==46169==  Uninitialised value was created by a heap allocation
==46169==    at 0x4843839: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==46169==    by 0x148CB3: __ftstringsetclass_MOD_addstring (FTStringSetClass.f90:240)
==46169==    by 0x149083: __ftstringsetclass_MOD_initwithstrings (FTStringSetClass.f90:177)
==46169==    by 0x123625: __controlfilereaderclass_MOD_initcontrolfilereader (ControlFileReader.f90:239)
==46169==    by 0x15491E: __hohqmeshmodule_MOD_readcontrolfile (HOHQMesh.f90:254)
==46169==    by 0x153C72: MAIN__ (HOHQMeshMain.f90:100)
==46169==    by 0x1542B1: main (HOHQMeshMain.f90:47)
```

Looks like the root of this is in `AddString` in the FTObjectLibrary in the call to release the local object pointer. 
```
232       SUBROUTINE AddString(self,str)
233          IMPLICIT NONE
234          CLASS(FTStringSet)          :: self
235          CHARACTER(LEN=*)            :: str
236          CLASS(FTObject)   , POINTER :: obj
237 
238          IF(self % dict % containsKey(key = str))     RETURN
239 
240          ALLOCATE(obj)
241          CALL self % dict % addObjectForKey(object = obj,key = str)
242          CALL release(obj)
243 
244       END SUBROUTINE AddString
```
Lines 300 and 308 are checking the value of the `refCount_` attribute for the `FTObject` pointer, which don't seem to get set. 

Should the `addObjectForKey` method set the `refCount_` when called ?

**Comment by DavidAKopriva** [comment]
Aha, that's a bug. The `obj' is allocated but not initialized, so it should not be released in line 242. The fix is to add after line 240:

CALL obj % retain()

(alternatively we would delete 242, but I think it is better to call dibs on something and then release when it is not needed anymore.) Note that for this class, the object is never used, it's just a pointer to nothing, which is why it is never initialized, just so that the Dictionary can be used to also represent a Set.

**Pull request merged**
